# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-web-config
  namespace: private-ai-app
data:
  APP_VERSION: v1.0.0
  FEATURE_STREAMING: "true"
  FEATURE_DOCUMENTS: "true"
  INFERENCE_PROFILE: balanced
